/* Uji mesin harga server: node alat/uji-harga.js */
'use strict';
const assert = require('assert');
const H = require('../harga');
let lulus = 0, gagal = 0;
function uji(nama, fn) { try { fn(); lulus++; console.log('LULUS  ' + nama); } catch (e) { gagal++; console.log('GAGAL  ' + nama + ' — ' + (e.message || e)); } }
const k = H.muat(require('path').join(require('os').tmpdir(), 'tidak-ada-' + process.pid + '.json'));   /* → jatuh ke harga-bawaan.json */
uji('katalog bawaan terbaca dari exo-data.js', () => { assert.ok(k.jasa.hourly && k.jasa.hourly.tarif === 78000); assert.strictEqual(k.biayaAplikasi, 3000); assert.strictEqual(k.juru.sw, 0.92); });
uji('rumus dasar = bulat(tarif × faktor) × jam + biaya aplikasi', () => { const r = H.hitungJasa({ jasa: 'hourly', jam: 3, juru: 'sw' }); assert.strictEqual(r.rincian.tarif, H.bulat(78000 * 0.92)); assert.strictEqual(r.total, r.rincian.tarif * 3 + 3000); });
uji('add-on & regu 2 orang', () => { const r = H.hitungJasa({ jasa: 'hourly', jam: 2, tambahan: ['fridge', 'window'], regu: 2 }); assert.strictEqual(r.rincian.addon, 105000); assert.strictEqual(r.rincian.biayaRegu, k.biayaRegu); assert.strictEqual(r.total, 78000 * 2 + 105000 + k.biayaRegu + 3000); });
uji('add-on asing ditolak', () => { assert.throws(() => H.hitungJasa({ jasa: 'hourly', jam: 2, tambahan: ['ferrari'] }), /Add-on tidak dikenal/); });
uji('langganan mingguan −10% dari dasar (hanya layanan yang boleh)', () => { const r = H.hitungJasa({ jasa: 'hourly', jam: 4, frekuensi: 'mingguan' }); assert.strictEqual(r.rincian.diskonLangganan, H.bulat(78000 * 4 * 0.10)); const s = H.hitungJasa({ jasa: 'deep', jam: 4, frekuensi: 'mingguan' }); assert.strictEqual(s.rincian.diskonLangganan, 0); });
uji('voucher CLEAN25 hanya bila subtotal ≥ minimum', () => { const r = H.hitungJasa({ jasa: 'hourly', jam: 2, voucher: 'clean25' }); assert.strictEqual(r.rincian.potonganVoucher, 25000); const s = H.hitungJasa({ jasa: 'hourly', jam: 2, voucher: 'clean25' }, Object.assign({}, k, { voucher: { CLEAN25: { potongan: 25000, min: 999999999 } } })); assert.strictEqual(s.rincian.potonganVoucher, 0); });
uji('flash deal aktif memotong dasar (dibulatkan ribuan)', () => { const kk = Object.assign({}, k, { flash: [{ jasa: 'hourly', diskonPct: 20, mulai: new Date(Date.now() - 1000).toISOString(), sampai: new Date(Date.now() + 3600000).toISOString() }] }); const r = H.hitungJasa({ jasa: 'hourly', jam: 3 }, kk); assert.strictEqual(r.rincian.flash, Math.round(78000 * 3 * 0.2 / 1000) * 1000); const kadaluwarsa = Object.assign({}, k, { flash: [{ jasa: 'hourly', diskonPct: 20, sampai: new Date(Date.now() - 1000).toISOString() }] }); assert.strictEqual(H.hitungJasa({ jasa: 'hourly', jam: 3 }, kadaluwarsa).rincian.flash, 0); });
uji('total tidak pernah negatif', () => { const kk = Object.assign({}, k, { voucher: { BESAR: { potongan: 99999999, min: 0 } } }); assert.strictEqual(H.hitungJasa({ jasa: 'hourly', jam: 2, voucher: 'BESAR' }, kk).total, 0); });
uji('validasi: jasa asing, jam 0, jam > 200, di bawah minimum, juru asing, faktor di luar batas', () => { assert.throws(() => H.hitungJasa({ jasa: 'x', jam: 1 })); assert.throws(() => H.hitungJasa({ jasa: 'hourly', jam: 0 })); assert.throws(() => H.hitungJasa({ jasa: 'hourly', jam: 999 })); assert.throws(() => H.hitungJasa({ jasa: 'care', jam: 2 }), /Minimal 4/); assert.throws(() => H.hitungJasa({ jasa: 'hourly', jam: 2, juru: 'hantu' })); assert.throws(() => H.hitungJasa({ jasa: 'hourly', jam: 2, juru: 'sw' }, Object.assign({}, k, { juru: { sw: 9 } })), /Faktor/); });
uji('klien tidak bisa menyelipkan tarif/amount sendiri', () => { const r = H.hitungJasa({ jasa: 'hourly', jam: 2, tarif: 1, amount: 1, total: 1 }); assert.strictEqual(r.total, 78000 * 2 + 3000); });
uji('tagihan akhir: asal + ekstra dalam batas; melebihi batas ditolak', () => { const r = H.hitungAkhir(300000, [{ nama: 'Cuci karpet', harga: 50000 }]); assert.strictEqual(r.total, 350000); assert.throws(() => H.hitungAkhir(300000, [{ nama: 'x', harga: 600000 }]), /per item/); assert.throws(() => H.hitungAkhir(300000, [{ nama: 'a', harga: 100000 }, { nama: 'b', harga: 100000 }]), /50%/); });
uji('tagihan: terikat sub, kedaluwarsa, sekali pakai', () => { const t = H.buatTagihan('subA', H.hitungJasa({ jasa: 'hourly', jam: 2 }), 'jasa'); assert.strictEqual(H.ambilTagihan(t.id, 'subA').total, t.total); assert.throws(() => H.ambilTagihan(t.id, 'subB'), /akun lain/); H.pakaiTagihan(t.id, 'EXO-1'); assert.throws(() => H.ambilTagihan(t.id, 'subA'), /sudah dipakai/); assert.throws(() => H.ambilTagihan('TG-tidak-ada', 'subA'), /tidak dikenal/); t.sampai = 0; const t2 = H.buatTagihan('subA', H.hitungJasa({ jasa: 'hourly', jam: 2 }), 'jasa'); t2.sampai = Date.now() - 1; assert.throws(() => H.ambilTagihan(t2.id, 'subA'), /kedaluwarsa/); });
uji('katalog terbitan admin divalidasi', () => { assert.throws(() => H.periksaKatalog({})); assert.throws(() => H.periksaKatalog({ jasa: { hourly: { tarif: -1 } } })); assert.strictEqual(H.periksaKatalog({ jasa: { hourly: { tarif: 80000 } } }), true); });
console.log('\n' + lulus + ' lulus, ' + gagal + ' gagal');
process.exit(gagal ? 1 : 0);
