/* ==========================================================================
   exo-privasi.js — kepatuhan UU PDP No. 27/2022 & PSE untuk EXOCLEAN
   --------------------------------------------------------------------------
   · Kebijakan privasi berversi (isi sesuai Pasal 21 UU PDP: identitas
     pengendali, dasar hukum, tujuan, jenis data, retensi, hak subjek, pihak
     ketiga, keamanan, kontak DPO) — bawaan di sini, terbitan admin di
     `exoclean_admin_pub.privasi`, tayang di privasi.html.
   · Persetujuan (Pasal 20–22): dicatat per sisi & versi kebijakan di tabel
     `persetujuanPdp` (waktu, versi, tujuan wajib, pilihan pemasaran, cara).
     Versi baru → pengguna diminta setuju ulang.
   · Hak subjek data (Pasal 5–13): akses/salinan (ekspor JSON), koreksi,
     penghapusan (penghapusan kriptografis lewat brankas), penarikan
     persetujuan, portabilitas — permintaan masuk tabel `permintaanPdp` dengan
     tenggat 3×24 jam (Pasal 32: akses wajib diberi dalam 3×24 jam).
   · Insiden kebocoran (Pasal 46): register `insidenPdp` dengan tenggat
     pemberitahuan 3×24 jam ke subjek data dan lembaga, plus surat templat.
   · Catatan kegiatan pemrosesan (RoPA, Pasal 31) diturunkan dari peta bidang
     pribadi brankas + tujuan per tabel.
   ========================================================================== */
var EXO_PRIVASI = (function () {
  'use strict';
  var VERSI_BAWAAN = '1.0';
  var BAWAAN = {
    versi: VERSI_BAWAAN, berlaku: '2026-09-08',
    pengendali: { nama:'PT EXOCLEAN Indonesia', alamat:'Jakarta Selatan, Indonesia', email:'privasi@exoclean.id', telp:'' },
    dpo: { nama:'Pejabat Pelindungan Data EXOCLEAN', email:'dpo@exoclean.id', telp:'' },
    bagian: [
      { id:'ruang', judul:'Ruang lingkup', isi:'Kebijakan ini berlaku untuk aplikasi EXOCLEAN (pelanggan, mitra cleaning, mitra toko), konsol operasional, web depan, dan layanan pendukungnya. Dengan mendaftar atau memakai layanan, Anda memberi persetujuan atas pemrosesan yang dijelaskan di sini sesuai UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi.' },
      { id:'data', judul:'Data yang kami kumpulkan', isi:'Pelanggan: nama, nomor telepon, email, alamat & koordinat lokasi layanan, riwayat pesanan, pembayaran (tanpa nomor kartu — diproses gateway berizin), ulasan, chat.\nMitra cleaning: identitas (nama, NIK/KTP untuk verifikasi, foto profil), dokumen SKCK & sertifikat, nomor rekening, lokasi saat bekerja, dua kontak darurat, absensi, kinerja.\nMitra toko: identitas pemilik, NIK/NPWP, rekening, alamat toko, data pesanan & pengiriman.\nData teknis: perangkat, alamat IP (disamarkan di log), catatan aktivitas keamanan.' },
      { id:'tujuan', judul:'Tujuan dan dasar hukum', isi:'Persetujuan Anda (Pasal 20): membuat akun, memproses pesanan dan pembayaran, menghubungkan pelanggan dengan mitra, pengiriman produk, layanan pelanggan.\nPemenuhan kontrak: menjalankan layanan yang Anda pesan atau kerjakan, pembayaran upah/pencairan.\nKepentingan sah & kewajiban hukum: verifikasi identitas mitra, pencegahan penipuan, keselamatan mitra (SOS & kontak darurat), pembukuan dan pajak, permintaan aparat yang sah.\nPemasaran (promo, notifikasi penawaran): hanya dengan persetujuan terpisah yang bisa ditarik kapan saja dari menu Privasi & data saya.' },
      { id:'retensi', judul:'Penyimpanan dan masa retensi', isi:'Data pribadi disimpan terenkripsi (AES-256-GCM, kunci per rekaman) di server EXOCLEAN di Indonesia; di perangkat hanya tersisa versi tersamar. Data akun disimpan selama akun aktif dan 5 tahun setelahnya untuk kewajiban pembukuan/pajak; lokasi mitra saat bekerja 90 hari; log keamanan 90 hari; dokumen identitas mitra dihapus setelah verifikasi selesai kecuali diwajibkan hukum. Setelah masa retensi, data dihapus secara kriptografis atau dianonimkan.' },
      { id:'pihak', judul:'Pihak ketiga (prosesor) dan transfer', isi:'Kami membagikan data seperlunya kepada: Midtrans/Xendit (pembayaran), Biteship dan kurir (pengiriman), Darmawisata (isi ulang & perjalanan), penyedia SMS/email OTP, Cloudflare (perlindungan bot), Google/Facebook (bila Anda memilih login sosial), dan penyedia server di Indonesia. Setiap prosesor terikat perjanjian pelindungan data. Kami tidak menjual data pribadi. Transfer ke luar Indonesia hanya bila negara tujuan punya tingkat pelindungan setara atau dengan pengamanan yang diwajibkan UU PDP.' },
      { id:'hak', judul:'Hak Anda sebagai subjek data', isi:'Anda berhak: mendapat informasi & salinan data Anda (kami penuhi dalam 3×24 jam), memperbaiki data yang keliru, menghapus data/akun, menarik persetujuan, membatasi atau menolak pemrosesan tertentu, memindahkan data (portabilitas), mengajukan keberatan atas keputusan otomatis, dan mendapat ganti rugi sesuai undang-undang. Ajukan lewat menu Privasi & data saya di aplikasi, email DPO, atau surat ke alamat pengendali. Kami tidak akan memperlakukan Anda berbeda karena menggunakan hak ini.' },
      { id:'keamanan', judul:'Keamanan', isi:'Enkripsi di server dan dalam perjalanan (TLS), OTP dan sesi bertanda tangan, PIN dan persetujuan dua orang untuk tindakan admin, log audit berantai, pembatasan akses berbasis peran, pengujian keamanan berkala, dan program pengungkapan kerentanan (keamanan.html). Tidak ada sistem yang sepenuhnya aman; bila terjadi kegagalan pelindungan yang berdampak pada Anda, kami memberi tahu Anda dan lembaga berwenang dalam 3×24 jam sejak diketahui.' },
      { id:'anak', judul:'Anak dan pengguna rentan', isi:'Layanan ditujukan untuk pengguna berusia 18 tahun ke atas. Pemrosesan data anak hanya dilakukan dengan persetujuan orang tua/wali sesuai Pasal 25 UU PDP.' },
      { id:'perubahan', judul:'Perubahan kebijakan', isi:'Setiap perubahan berarti akan diberi nomor versi dan tanggal berlaku baru; Anda akan diminta menyetujui ulang di aplikasi sebelum melanjutkan. Riwayat versi tersedia di halaman ini.' }
    ],
    tujuanWajib: ['akun', 'layanan', 'pembayaran', 'keselamatan'], tujuanPilihan: ['pemasaran']
  };
  var HAK = { akses:'Akses & salinan data', koreksi:'Perbaikan data', hapus:'Penghapusan data / akun', tarik:'Penarikan persetujuan', portabilitas:'Portabilitas data', keberatan:'Keberatan atas pemrosesan' };
  var STATUS_PERMINTAAN = { baru:'Baru', diproses:'Diproses', selesai:'Selesai', ditolak:'Ditolak' };
  var TENGGAT_JAM = 72;
  function db() { try { return window.EXO_DB && EXO_DB.init() ? EXO_DB : null; } catch (e) { return null; } }
  function kini() { return new Date().toISOString(); }
  function pub() { try { return JSON.parse(localStorage.getItem('exoclean_admin_pub') || '{}') || {}; } catch (e) { return {}; } }
  function kebijakan(rancangan) { var src = rancangan || pub().privasi || null; var k = Object.assign({}, BAWAAN, src || {}); k.pengendali = Object.assign({}, BAWAAN.pengendali, (src && src.pengendali) || {}); k.dpo = Object.assign({}, BAWAAN.dpo, (src && src.dpo) || {}); k.bagian = (src && src.bagian && src.bagian.length) ? src.bagian : BAWAAN.bagian; return k; }
  function versiKini() { return kebijakan().versi; }

  /* ---------- persetujuan ---------- */
  function subjek(sisi) { return String(sisi || 'customer'); }
  function persetujuan(sisi) { var d = db(); if (!d) return null; var s = subjek(sisi); return d.all('persetujuanPdp').filter(function (p) { return p.subjek === s && !p.ditarikAt; }).sort(function (a, b) { return String(b.at).localeCompare(String(a.at)); })[0] || null; }
  function perluSetuju(sisi) { var p = persetujuan(sisi); return !p || p.versi !== versiKini(); }
  function setuju(sisi, pilihan, cara) { var d = db(); if (!d) return null; var k = kebijakan(); return d.insert('persetujuanPdp', { subjek:subjek(sisi), sisi:sisi, versi:k.versi, berlaku:k.berlaku, tujuan:k.tujuanWajib.slice(), pemasaran:!!(pilihan && pilihan.pemasaran), cara:cara || 'aplikasi', agen:(navigator.userAgent || '').slice(0, 120), at:kini() }); }
  function ubahPemasaran(sisi, nilai) { var d = db(), p = persetujuan(sisi); if (!d || !p) return null; return d.update('persetujuanPdp', p.id, { pemasaran:!!nilai, pemasaranDiubahAt:kini() }); }
  function tarikSemua(sisi) { var d = db(); if (!d) return; d.all('persetujuanPdp').filter(function (p) { return p.subjek === subjek(sisi) && !p.ditarikAt; }).forEach(function (p) { d.update('persetujuanPdp', p.id, { ditarikAt:kini() }); }); }
  function statistikPersetujuan() { var d = db(); if (!d) return {}; var out = { total:0, versi:{}, pemasaran:0, ditarik:0 }; d.all('persetujuanPdp').forEach(function (p) { out.total++; out.versi[p.versi] = (out.versi[p.versi] || 0) + 1; if (p.pemasaran) out.pemasaran++; if (p.ditarikAt) out.ditarik++; }); return out; }

  /* ---------- hak subjek data ---------- */
  function mintaHak(sisi, jenis, catatan, kontak) { var d = db(); if (!d || !HAK[jenis]) return null; var at = new Date(); return d.insert('permintaanPdp', { no:'PDP-' + at.toISOString().slice(0, 10).replace(/-/g, '') + '-' + Math.random().toString(36).slice(2, 6).toUpperCase(), subjek:subjek(sisi), sisi:sisi, jenis:jenis, catatan:String(catatan || '').slice(0, 500), kontak:String(kontak || '').slice(0, 120), status:'baru', at:at.toISOString(), tenggat:new Date(at.getTime() + TENGGAT_JAM * 3600000).toISOString() }); }
  function permintaanSaya(sisi) { var d = db(); return d ? d.all('permintaanPdp').filter(function (p) { return p.subjek === subjek(sisi); }).sort(function (a, b) { return String(b.at).localeCompare(String(a.at)); }) : []; }
  function semuaPermintaan() { var d = db(); return d ? d.all('permintaanPdp').sort(function (a, b) { return String(b.at).localeCompare(String(a.at)); }) : []; }
  function tenggatLewat(p) { return p.status !== 'selesai' && p.status !== 'ditolak' && new Date(p.tenggat).getTime() < Date.now(); }
  /* Tabel mana yang "milik" tiap sisi (untuk ekspor & hapus) */
  var TABEL_SISI = { customer:{ users:function (r) { return r.role === 'client'; }, orders:function () { return true; }, complaints:function () { return true; }, ratings:function () { return true; }, pesananToko:function () { return true; } }, partner:{ users:function (r) { return r.role === 'worker'; }, kontakDarurat:function () { return true; }, absensi:function () { return true; }, sosInsiden:function () { return true; }, jobLapangan:function () { return true; }, sertifikat:function () { return true; }, pendaftaran:function () { return true; } }, toko:{ toko:function () { return true; }, penarikanToko:function () { return true; } } };
  function eksporSaya(sisi) { var d = db(), peta = TABEL_SISI[sisi] || TABEL_SISI.customer, out = { subjek:subjek(sisi), diekspor:kini(), versiKebijakan:versiKini(), persetujuan:d ? d.all('persetujuanPdp').filter(function (p) { return p.subjek === subjek(sisi); }) : [], data:{} }; if (!d) return out; Object.keys(peta).forEach(function (t) { out.data[t] = d.all(t).filter(peta[t]).map(function (r) { var c = Object.assign({}, r); delete c._brankas; delete c.passHash; delete c.pinHash; return c; }); }); return out; }
  /* Penghapusan: rekaman brankas dihapus (kriptografis), baris lokal dianonimkan — riwayat transaksi tetap untuk kewajiban pembukuan */
  function hapusSubjek(sisi) { var d = db(), peta = TABEL_SISI[sisi] || TABEL_SISI.customer, n = 0, brankas = window.EXO_BRANKAS; if (!d) return 0; Object.keys(peta).forEach(function (t) { d.all(t).filter(peta[t]).forEach(function (r) { var bidang = brankas && brankas.BIDANG[t] ? brankas.BIDANG[t].bidang : []; var patch = { dianonimkanAt:kini() }; bidang.forEach(function (b) { if (r[b] != null) patch[b] = null; }); if (r.nama) patch.nama = 'Pengguna dihapus'; if (r.email) patch.email = null; patch._brankas = null; d.update(t, r.id, patch); if (brankas && brankas.aktif && brankas.aktif()) brankas.hapus(t, r.id); n++; }); }); tarikSemua(sisi); return n; }

  /* ---------- insiden kebocoran (Pasal 46) ---------- */
  function catatInsiden(isi) { var d = db(); if (!d) return null; var diketahui = isi.diketahuiAt || kini(); return d.insert('insidenPdp', { no:'INS-' + diketahui.slice(0, 10).replace(/-/g, '') + '-' + Math.random().toString(36).slice(2, 5).toUpperCase(), judul:String(isi.judul || '').slice(0, 160), jenisData:String(isi.jenisData || '').slice(0, 300), jumlahSubjek:Number(isi.jumlahSubjek) || 0, penyebab:String(isi.penyebab || '').slice(0, 500), langkah:String(isi.langkah || '').slice(0, 800), diketahuiAt:diketahui, tenggat:new Date(new Date(diketahui).getTime() + TENGGAT_JAM * 3600000).toISOString(), status:'terbuka', pemberitahuanSubjekAt:null, pemberitahuanLembagaAt:null, at:kini() }); }
  function semuaInsiden() { var d = db(); return d ? d.all('insidenPdp').sort(function (a, b) { return String(b.at).localeCompare(String(a.at)); }) : []; }
  function sisaJam(iso) { return Math.round((new Date(iso).getTime() - Date.now()) / 3600000); }
  function suratPemberitahuan(ins, kepada) {
    var k = kebijakan(), tgl = new Date().toLocaleDateString('id-ID', { day:'numeric', month:'long', year:'numeric' });
    if (kepada === 'lembaga') return ['Kepada Yth. Lembaga Penyelenggara Pelindungan Data Pribadi', 'Perihal: Pemberitahuan kegagalan pelindungan data pribadi (Pasal 46 UU No. 27/2022)', '', 'Pengendali data: ' + k.pengendali.nama + ' (' + k.pengendali.email + ')', 'Pejabat Pelindungan Data: ' + k.dpo.nama + ' (' + k.dpo.email + ')', 'Nomor insiden: ' + ins.no + ' · diketahui ' + ins.diketahuiAt.replace('T', ' ').slice(0, 16) + ' WIB', '', '1. Data pribadi yang terungkap: ' + ins.jenisData, '2. Jumlah subjek data terdampak (perkiraan): ' + ins.jumlahSubjek, '3. Kapan dan bagaimana terjadi: ' + ins.penyebab, '4. Upaya penanganan dan pemulihan: ' + ins.langkah, '5. Pemberitahuan kepada subjek data: ' + (ins.pemberitahuanSubjekAt ? 'sudah, ' + ins.pemberitahuanSubjekAt.slice(0, 16) : 'dalam proses'), '', 'Jakarta, ' + tgl, k.pengendali.nama].join('\n');
    return ['Kepada pengguna EXOCLEAN yang terhormat,', '', 'Kami memberi tahu adanya kegagalan pelindungan data pribadi yang mungkin berdampak pada Anda (nomor insiden ' + ins.no + ').', '', 'Data yang terdampak: ' + ins.jenisData + '.', 'Kapan dan bagaimana: ' + ins.penyebab + '.', 'Yang sudah kami lakukan: ' + ins.langkah + '.', '', 'Yang dapat Anda lakukan: waspadai pesan/telepon yang mengatasnamakan EXOCLEAN, jangan pernah membagikan kode OTP, dan ganti sandi bila Anda memakainya di layanan lain.', '', 'Pertanyaan dan permintaan bantuan: ' + k.dpo.email + (k.dpo.telp ? ' / ' + k.dpo.telp : '') + '.', '', 'Kami mohon maaf atas kejadian ini. — ' + k.pengendali.nama + ', ' + tgl].join('\n');
  }

  /* ---------- catatan kegiatan pemrosesan (RoPA, Pasal 31) ---------- */
  var TUJUAN_TABEL = { users:['Akun & identitas', 'Persetujuan / kontrak', 'selama akun aktif + 5 tahun'], orders:['Pemesanan & pelaksanaan layanan', 'Kontrak', '5 tahun (pembukuan)'], kontakDarurat:['Keselamatan mitra (SOS)', 'Kepentingan sah / persetujuan mitra', 'selama kemitraan'], toko:['Verifikasi & pencairan mitra toko', 'Kontrak / kewajiban hukum (pajak)', 'selama kemitraan + 5 tahun'], penarikanToko:['Pencairan dana', 'Kontrak', '5 tahun'], pendaftaran:['Verifikasi mitra', 'Kewajiban hukum / persetujuan', 'dihapus setelah verifikasi'], sosInsiden:['Tanggap darurat', 'Kepentingan vital', '1 tahun'], foto:['Verifikasi identitas & bukti layanan', 'Persetujuan', 'dihapus setelah verifikasi / 90 hari'], vdp:['Program pengungkapan kerentanan', 'Persetujuan pelapor', '2 tahun'] };
  function catatanPemrosesan() { var B = window.EXO_BRANKAS ? EXO_BRANKAS.BIDANG : {}; return Object.keys(TUJUAN_TABEL).map(function (t) { var u = TUJUAN_TABEL[t]; return { tabel:t, tujuan:u[0], dasar:u[1], retensi:u[2], bidang:B[t] ? B[t].bidang.slice() : [], terenkripsi:!!B[t] || t === 'foto' || t === 'vdp' }; }); }

  /* ---------- status kepatuhan (diisi admin) ---------- */
  function kepatuhan() { var d = db(); return Object.assign({ pse:{ status:'belum', nomor:'', tgl:'', nib:'' }, dpo:{ nama:'', email:'', ditunjukAt:'' }, dpia:{ status:'belum', tgl:'', catatan:'' }, prosesor:[{ nama:'Midtrans / Xendit', peran:'pembayaran', perjanjian:'belum' }, { nama:'Biteship', peran:'pengiriman', perjanjian:'belum' }, { nama:'Darmawisata', peran:'PPOB & perjalanan', perjanjian:'belum' }, { nama:'Penyedia SMS/email OTP', peran:'OTP', perjanjian:'belum' }, { nama:'Penyedia server', peran:'hosting di Indonesia', perjanjian:'belum' }] }, d ? (d.setting('pdpKepatuhan') || {}) : {}); }
  function simpanKepatuhan(k) { var d = db(); if (d) d.setting('pdpKepatuhan', k); return k; }
  function skorKepatuhan() { var k = kepatuhan(), p = kebijakan(), item = [['Kebijakan privasi diterbitkan', !!pub().privasi], ['Persetujuan dicatat per versi', statistikPersetujuan().total > 0], ['PSE Lingkup Privat terdaftar', k.pse.status === 'terdaftar'], ['DPO ditunjuk', !!k.dpo.email], ['DPIA selesai', k.dpia.status === 'selesai'], ['Perjanjian prosesor lengkap', k.prosesor.every(function (x) { return x.perjanjian === 'ada'; })], ['Data pribadi terenkripsi di server', !!(window.EXO_BRANKAS && EXO_BRANKAS.ringkas().sehat)], ['Prosedur insiden 3×24 jam siap', true], ['Tidak ada permintaan subjek lewat tenggat', !semuaPermintaan().some(tenggatLewat)]]; return { item:item, nilai:item.filter(function (i) { return i[1]; }).length, total:item.length, versi:p.versi }; }
  return { BAWAAN:BAWAAN, HAK:HAK, STATUS_PERMINTAAN:STATUS_PERMINTAAN, TENGGAT_JAM:TENGGAT_JAM, kebijakan:kebijakan, versiKini:versiKini, persetujuan:persetujuan, perluSetuju:perluSetuju, setuju:setuju, ubahPemasaran:ubahPemasaran, tarikSemua:tarikSemua, statistikPersetujuan:statistikPersetujuan, mintaHak:mintaHak, permintaanSaya:permintaanSaya, semuaPermintaan:semuaPermintaan, tenggatLewat:tenggatLewat, eksporSaya:eksporSaya, hapusSubjek:hapusSubjek, catatInsiden:catatInsiden, semuaInsiden:semuaInsiden, sisaJam:sisaJam, suratPemberitahuan:suratPemberitahuan, catatanPemrosesan:catatanPemrosesan, kepatuhan:kepatuhan, simpanKepatuhan:simpanKepatuhan, skorKepatuhan:skorKepatuhan };
})();
